name: anime

on: push

defaults:
  run:
    shell: bash

jobs:
  serious-work:
    # This belongs here
    runs-on: ubuntu-latest

    # And these are steps
    steps:
      - name: Is this thing working
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"

